"""empty message

Revision ID: 251ac0f157f8
Revises: 77f3031e9921
Create Date: 2024-11-07 14:56:50.969636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251ac0f157f8'
down_revision = '77f3031e9921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
